services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scramble_dev
    volumes:
      - scramble_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    command: mix phx.server
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      - .:/scramble

volumes:
  scramble_data:
